# This just uses npm and gh-pages to publish.
name: Publish to gh-pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Create env file
        run: >
          touch .env
          echo BASE_PATH=/siggraph-website >> .env
          cat .env
    - run: npm install
    - name: Build and export
      run: npm run export
    - name: Publish to Github Pages
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
