# "Tests" our build process.
name: Run build process

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Create env file
      run: |
        touch .env
        echo BASE_PATH=/siggraph-website >> .env
        cat .env
    - run: npm install
    - name: Build and export
      run: npm run export
